name: update bench metrics
on:
  push:
    branches: [ main ]
    paths:
      - 'generate-*/**/*.js'
      - 'scripts/bench.mjs'
      - '.github/workflows/bench.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'generate-*/**/*.js'
      - 'scripts/bench.mjs'
      - '.github/workflows/bench.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run benchmarks
        run: |
          set -euo pipefail
          node scripts/bench.mjs
        continue-on-error: true
      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add bench/*.json || true
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git pull --rebase origin main || true
            git commit -m "chore(bench): refresh ops/s badges"
            git push
          fi
